# Generated by Django 4.2.7 on 2026-02-19 05:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('site_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.TextField(blank=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('project_id', models.CharField(blank=True, max_length=100)),
                ('ladder', models.CharField(blank=True, max_length=50)),
                ('sla', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['site_name'],
                'indexes': [models.Index(fields=['site_code'], name='monitor_sit_site_co_173460_idx'), models.Index(fields=['is_active'], name='monitor_sit_is_acti_6984d6_idx')],
            },
        ),
        migrations.CreateModel(
            name='RectifierData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField(db_index=True)),
                ('site_name', models.CharField(default='', max_length=255)),
                ('project_id', models.CharField(default='', max_length=255)),
                ('ladder', models.CharField(default='', max_length=100)),
                ('sla', models.CharField(default='', max_length=100)),
                ('status_realtime', models.CharField(db_index=True, default='Normal', max_length=50)),
                ('status_ladder', models.CharField(default='Normal', max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('door_cabinet', models.CharField(default='Close', max_length=20)),
                ('battery_stolen', models.CharField(default='Close', max_length=20)),
                ('temperature', models.FloatField(default=0)),
                ('humidity', models.FloatField(default=0)),
                ('vac_input_l1', models.FloatField(default=0)),
                ('vac_input_l2', models.FloatField(default=0)),
                ('vac_input_l3', models.FloatField(blank=True, null=True)),
                ('vdc_output', models.FloatField(default=0)),
                ('battery_current', models.FloatField(default=0)),
                ('iac_input_l1', models.FloatField(blank=True, null=True)),
                ('iac_input_l2', models.FloatField(blank=True, null=True)),
                ('iac_input_l3', models.FloatField(blank=True, null=True)),
                ('load_current', models.FloatField(default=0)),
                ('load_power', models.FloatField(default=0)),
                ('pac_load_l1', models.FloatField(default=0)),
                ('pac_load_l2', models.FloatField(default=0)),
                ('pac_load_l3', models.FloatField(default=0)),
                ('rectifier_current', models.FloatField(default=0)),
                ('total_power', models.FloatField(default=0)),
                ('battery_bank_1_voltage', models.FloatField(default=0)),
                ('battery_bank_1_current', models.FloatField(default=0)),
                ('battery_bank_1_soc', models.FloatField(default=100)),
                ('battery_bank_1_soh', models.FloatField(default=100)),
                ('battery_bank_2_voltage', models.FloatField(default=0)),
                ('battery_bank_2_current', models.FloatField(default=0)),
                ('battery_bank_2_soc', models.FloatField(default=100)),
                ('battery_bank_2_soh', models.FloatField(default=100)),
                ('battery_bank_3_voltage', models.FloatField(default=0)),
                ('battery_bank_3_current', models.FloatField(default=0)),
                ('battery_bank_3_soc', models.FloatField(default=100)),
                ('battery_bank_3_soh', models.FloatField(default=100)),
                ('backup_duration', models.IntegerField(blank=True, null=True)),
                ('time_remaining', models.IntegerField(blank=True, null=True)),
                ('battery_status', models.CharField(default='Standby', max_length=50)),
                ('start_backup', models.CharField(default='No data', max_length=100)),
                ('soc_avg', models.FloatField(default=100)),
                ('modules_status', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rectifier_data', to='monitor.site')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['site', '-timestamp'], name='monitor_rec_site_id_05fb97_idx'), models.Index(fields=['-timestamp'], name='monitor_rec_timesta_8460ec_idx'), models.Index(fields=['status_realtime'], name='monitor_rec_status__26aa99_idx')],
            },
        ),
    ]
